// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main application service exposed to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as categories$0 from "./internal/categories/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mods$0 from "./internal/mods/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nexus$0 from "./internal/nexus/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profiles$0 from "./internal/profiles/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as smapi$0 from "./internal/smapi/models.js";

/**
 * @param {string} categoryID
 * @param {string} modID
 * @returns {$CancellablePromise<void>}
 */
export function AssignModToCategory(categoryID, modID) {
    return $Call.ByID(829775581, categoryID, modID);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function BrowseGameFolder() {
    return $Call.ByID(4139091597);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function BrowseModsRoot() {
    return $Call.ByID(4008213038);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function BrowseSMAPIPath() {
    return $Call.ByID(3769594114);
}

/**
 * SelfUpdate checks for application updates (placeholder for release channel).
 * @returns {$CancellablePromise<string>}
 */
export function CheckAppUpdate() {
    return $Call.ByID(3342248195);
}

/**
 * @returns {$CancellablePromise<smapi$0.ModUpdateResult[]>}
 */
export function CheckModUpdates() {
    return $Call.ByID(2723178493).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<smapi$0.UpdateInfo>}
 */
export function CheckSMAPIUpdate() {
    return $Call.ByID(2834063480).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} gamePath
 * @param {string} smapiPath
 * @param {string} modsRoot
 * @returns {$CancellablePromise<void>}
 */
export function CompleteSetup(gamePath, smapiPath, modsRoot) {
    return $Call.ByID(507086583, gamePath, smapiPath, modsRoot);
}

/**
 * @param {string} name
 * @param {string} color
 * @returns {$CancellablePromise<categories$0.Category>}
 */
export function CreateCategory(name, color) {
    return $Call.ByID(4163536593, name, color).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<profiles$0.Profile>}
 */
export function CreateProfile(name) {
    return $Call.ByID(2723389902, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCategory(id) {
    return $Call.ByID(988551738, id);
}

/**
 * @param {string} folderPath
 * @param {boolean} deleteArchive
 * @returns {$CancellablePromise<void>}
 */
export function DeleteMod(folderPath, deleteArchive) {
    return $Call.ByID(4063556150, folderPath, deleteArchive);
}

/**
 * @param {string[]} folderPaths
 * @param {boolean} deleteArchives
 * @returns {$CancellablePromise<mods$0.DeleteModsResult>}
 */
export function DeleteMods(folderPaths, deleteArchives) {
    return $Call.ByID(2388222623, folderPaths, deleteArchives).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProfile(id) {
    return $Call.ByID(2457157279, id);
}

/**
 * @param {string} archivePath
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSavedDownload(archivePath) {
    return $Call.ByID(2025264765, archivePath);
}

/**
 * @returns {$CancellablePromise<config$0.DetectionResult>}
 */
export function DetectPaths() {
    return $Call.ByID(2789414126).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} updateKey
 * @param {string} modName
 * @returns {$CancellablePromise<string>}
 */
export function DownloadModUpdate(updateKey, modName) {
    return $Call.ByID(1363034302, updateKey, modName);
}

/**
 * EmitNXMURL notifies the frontend to handle an nxm:// link.
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function EmitNXMURL(url) {
    return $Call.ByID(1591671804, url);
}

/**
 * @param {string} updateKey
 * @param {string} version
 * @returns {$CancellablePromise<void>}
 */
export function EndorseMod(updateKey, version) {
    return $Call.ByID(2935554337, updateKey, version);
}

/**
 * GetNexusSuggestedTags maps Nexus mod page categories to existing user tag IDs.
 * @param {number[]} modIDs
 * @returns {$CancellablePromise<string[]>}
 */
export function GetNexusSuggestedTags(modIDs) {
    return $Call.ByID(2488253240, modIDs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetSMAPIVersion() {
    return $Call.ByID(364360755);
}

/**
 * @returns {$CancellablePromise<config$0.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(2554697378).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} locale
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetTranslations(locale) {
    return $Call.ByID(3594757519, locale).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<string>}
 */
export function HandleNXMURL(url) {
    return $Call.ByID(1544860105, url);
}

/**
 * @param {string[]} archivePaths
 * @returns {$CancellablePromise<mods$0.InstallResult[]>}
 */
export function InstallMods(archivePaths) {
    return $Call.ByID(2855435565, archivePaths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function InstallSMAPI() {
    return $Call.ByID(3004263564);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsNexusConnected() {
    return $Call.ByID(505497159);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function LaunchSMAPI() {
    return $Call.ByID(3891984186);
}

/**
 * @returns {$CancellablePromise<categories$0.Category[]>}
 */
export function ListCategories() {
    return $Call.ByID(1403045529).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @returns {$CancellablePromise<nexus$0.DownloadEntry[]>}
 */
export function ListDownloads() {
    return $Call.ByID(2520899730).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @param {string} search
 * @param {string} hideDisabled
 * @returns {$CancellablePromise<mods$0.ModGroup[]>}
 */
export function ListModGroups(search, hideDisabled) {
    return $Call.ByID(3343994023, search, hideDisabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @param {string} search
 * @param {string} hideDisabled
 * @returns {$CancellablePromise<mods$0.Mod[]>}
 */
export function ListMods(search, hideDisabled) {
    return $Call.ByID(4207468124, search, hideDisabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @returns {$CancellablePromise<profiles$0.Profile[]>}
 */
export function ListProfiles() {
    return $Call.ByID(1957526603).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * @returns {$CancellablePromise<nexus$0.DownloadRecord[]>}
 */
export function ListSavedDownloads() {
    return $Call.ByID(2754041041).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function ModsReadyToUpdate() {
    return $Call.ByID(3040771715);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function ModsWithDependencyIssues() {
    return $Call.ByID(2187278053);
}

/**
 * @param {string} folderPath
 * @returns {$CancellablePromise<void>}
 */
export function OpenManifest(folderPath) {
    return $Call.ByID(1612629304, folderPath);
}

/**
 * @param {string} folderPath
 * @returns {$CancellablePromise<void>}
 */
export function OpenModFolder(folderPath) {
    return $Call.ByID(3603050635, folderPath);
}

/**
 * @param {string[]} archivePaths
 * @returns {$CancellablePromise<mods$0.InstallDependencyPreview[]>}
 */
export function PreviewInstallDependencies(archivePaths) {
    return $Call.ByID(3625388851, archivePaths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * ProcessCommandLineArgs handles nxm:// URLs passed on startup.
 * @param {string[]} args
 * @returns {$CancellablePromise<void>}
 */
export function ProcessCommandLineArgs(args) {
    return $Call.ByID(24794552, args);
}

/**
 * RegisterNXMProtocol registers nxm:// to launch this app (Windows, current user).
 * @returns {$CancellablePromise<void>}
 */
export function RegisterNXMProtocol() {
    return $Call.ByID(2861492769);
}

/**
 * @param {string} id
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RenameProfile(id, name) {
    return $Call.ByID(1067637764, id, name);
}

/**
 * @param {string[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function ReorderCategories(ids) {
    return $Call.ByID(3631475484, ids);
}

/**
 * @param {string} archivePath
 * @returns {$CancellablePromise<void>}
 */
export function RevealArchiveInFileManager(archivePath) {
    return $Call.ByID(269732774, archivePath);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SaveProfile() {
    return $Call.ByID(406053493);
}

/**
 * @param {config$0.Settings} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(1949631069, settings);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function SelectArchives() {
    return $Call.ByID(4279671618).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SetActiveProfile(id) {
    return $Call.ByID(3598325438, id);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApplication(app) {
    return $Call.ByID(4121261467, app);
}

/**
 * @param {string} id
 * @param {boolean} visible
 * @returns {$CancellablePromise<void>}
 */
export function SetCategoryVisibility(id, visible) {
    return $Call.ByID(4161271547, id, visible);
}

/**
 * @param {string} modID
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetModEnabled(modID, enabled) {
    return $Call.ByID(1151537538, modID, enabled);
}

/**
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function SetNexusAPIKey(key) {
    return $Call.ByID(127370205, key);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Startup() {
    return $Call.ByID(2154875234);
}

/**
 * @param {string} categoryID
 * @param {string} modID
 * @returns {$CancellablePromise<void>}
 */
export function UnassignModFromCategory(categoryID, modID) {
    return $Call.ByID(3431169981, categoryID, modID);
}

/**
 * @param {string} id
 * @param {string} name
 * @param {string} color
 * @param {boolean} visible
 * @param {number} sortOrder
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCategory(id, name, color, visible, sortOrder) {
    return $Call.ByID(2178518964, id, name, color, visible, sortOrder);
}

/**
 * @param {string} folderPath
 * @param {string} archivePath
 * @param {boolean} deleteOld
 * @returns {$CancellablePromise<void>}
 */
export function UpdateMod(folderPath, archivePath, deleteOld) {
    return $Call.ByID(1693017024, folderPath, archivePath, deleteOld);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function ValidateNexusAPIKey() {
    return $Call.ByID(705135029);
}

// Private type creation functions
const $$createType0 = smapi$0.ModUpdateResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = smapi$0.UpdateInfo.createFrom;
const $$createType3 = categories$0.Category.createFrom;
const $$createType4 = profiles$0.Profile.createFrom;
const $$createType5 = mods$0.DeleteModsResult.createFrom;
const $$createType6 = config$0.DetectionResult.createFrom;
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = config$0.Settings.createFrom;
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = mods$0.InstallResult.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Array($$createType3);
const $$createType13 = nexus$0.DownloadEntry.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = mods$0.ModGroup.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = mods$0.Mod.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $Create.Array($$createType4);
const $$createType20 = nexus$0.DownloadRecord.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = mods$0.InstallDependencyPreview.createFrom;
const $$createType23 = $Create.Array($$createType22);
