// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main application service exposed to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as categories$0 from "./internal/categories/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mods$0 from "./internal/mods/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nexus$0 from "./internal/nexus/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profiles$0 from "./internal/profiles/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as smapi$0 from "./internal/smapi/models.js";

export function AssignModToCategory(categoryID: string, modID: string): $CancellablePromise<void> {
    return $Call.ByID(829775581, categoryID, modID);
}

export function BrowseGameFolder(): $CancellablePromise<string> {
    return $Call.ByID(4139091597);
}

export function BrowseModsRoot(): $CancellablePromise<string> {
    return $Call.ByID(4008213038);
}

export function BrowseSMAPIPath(): $CancellablePromise<string> {
    return $Call.ByID(3769594114);
}

/**
 * SelfUpdate checks for application updates (placeholder for release channel).
 */
export function CheckAppUpdate(): $CancellablePromise<string> {
    return $Call.ByID(3342248195);
}

export function CheckModUpdates(): $CancellablePromise<smapi$0.ModUpdateResult[] | null> {
    return $Call.ByID(2723178493);
}

export function CheckSMAPIUpdate(): $CancellablePromise<smapi$0.UpdateInfo> {
    return $Call.ByID(2834063480);
}

export function CompleteSetup(gamePath: string, smapiPath: string, modsRoot: string): $CancellablePromise<void> {
    return $Call.ByID(507086583, gamePath, smapiPath, modsRoot);
}

export function CreateCategory(name: string, color: string): $CancellablePromise<categories$0.Category> {
    return $Call.ByID(4163536593, name, color);
}

export function CreateProfile(name: string): $CancellablePromise<profiles$0.Profile> {
    return $Call.ByID(2723389902, name);
}

export function DeleteCategory(id: string): $CancellablePromise<void> {
    return $Call.ByID(988551738, id);
}

export function DeleteMod(folderPath: string, deleteArchive: boolean): $CancellablePromise<void> {
    return $Call.ByID(4063556150, folderPath, deleteArchive);
}

export function DeleteMods(folderPaths: string[] | null, deleteArchives: boolean): $CancellablePromise<mods$0.DeleteModsResult> {
    return $Call.ByID(2388222623, folderPaths, deleteArchives);
}

export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(2457157279, id);
}

export function DeleteSavedDownload(archivePath: string): $CancellablePromise<void> {
    return $Call.ByID(2025264765, archivePath);
}

export function DetectPaths(): $CancellablePromise<config$0.DetectionResult> {
    return $Call.ByID(2789414126);
}

export function DownloadModUpdate(updateKey: string, modName: string): $CancellablePromise<string> {
    return $Call.ByID(1363034302, updateKey, modName);
}

/**
 * EmitNXMURL notifies the frontend to handle an nxm:// link.
 */
export function EmitNXMURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(1591671804, url);
}

export function EndorseMod(updateKey: string, version: string): $CancellablePromise<void> {
    return $Call.ByID(2935554337, updateKey, version);
}

/**
 * GetNexusSuggestedTags maps Nexus mod page categories to existing user tag IDs.
 */
export function GetNexusSuggestedTags(modIDs: number[] | null): $CancellablePromise<string[] | null> {
    return $Call.ByID(2488253240, modIDs);
}

export function GetSMAPIVersion(): $CancellablePromise<string> {
    return $Call.ByID(364360755);
}

export function GetSettings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(2554697378);
}

export function GetTranslations(locale: string): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(3594757519, locale);
}

export function HandleNXMURL(url: string): $CancellablePromise<string> {
    return $Call.ByID(1544860105, url);
}

export function InstallMods(archivePaths: string[] | null, useFolderDisplayNames: boolean): $CancellablePromise<mods$0.InstallResult[] | null> {
    return $Call.ByID(2855435565, archivePaths, useFolderDisplayNames);
}

export function InstallSMAPI(): $CancellablePromise<void> {
    return $Call.ByID(3004263564);
}

export function IsNexusConnected(): $CancellablePromise<boolean> {
    return $Call.ByID(505497159);
}

export function LaunchSMAPI(): $CancellablePromise<void> {
    return $Call.ByID(3891984186);
}

export function ListCategories(): $CancellablePromise<categories$0.Category[] | null> {
    return $Call.ByID(1403045529);
}

export function ListDownloads(): $CancellablePromise<nexus$0.DownloadEntry[] | null> {
    return $Call.ByID(2520899730);
}

export function ListModGroups(search: string, hideDisabled: string): $CancellablePromise<mods$0.ModGroup[] | null> {
    return $Call.ByID(3343994023, search, hideDisabled);
}

export function ListMods(search: string, hideDisabled: string): $CancellablePromise<mods$0.Mod[] | null> {
    return $Call.ByID(4207468124, search, hideDisabled);
}

export function ListProfiles(): $CancellablePromise<profiles$0.Profile[] | null> {
    return $Call.ByID(1957526603);
}

export function ListSavedDownloads(): $CancellablePromise<nexus$0.DownloadRecord[] | null> {
    return $Call.ByID(2754041041);
}

export function ModsReadyToUpdate(): $CancellablePromise<number> {
    return $Call.ByID(3040771715);
}

export function ModsWithDependencyIssues(): $CancellablePromise<number> {
    return $Call.ByID(2187278053);
}

export function OpenManifest(folderPath: string): $CancellablePromise<void> {
    return $Call.ByID(1612629304, folderPath);
}

export function OpenModFolder(folderPath: string): $CancellablePromise<void> {
    return $Call.ByID(3603050635, folderPath);
}

export function PreviewInstallDependencies(archivePaths: string[] | null): $CancellablePromise<mods$0.InstallDependencyPreview[] | null> {
    return $Call.ByID(3625388851, archivePaths);
}

export function PreviewInstallNames(archivePaths: string[] | null): $CancellablePromise<mods$0.InstallNamePreview[] | null> {
    return $Call.ByID(471547458, archivePaths);
}

/**
 * ProcessCommandLineArgs handles nxm:// URLs passed on startup.
 */
export function ProcessCommandLineArgs(args: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(24794552, args);
}

/**
 * RegisterNXMProtocol registers nxm:// to launch this app (Windows, current user).
 */
export function RegisterNXMProtocol(): $CancellablePromise<void> {
    return $Call.ByID(2861492769);
}

export function RenameProfile(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1067637764, id, name);
}

export function ReorderCategories(ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3631475484, ids);
}

export function RevealArchiveInFileManager(archivePath: string): $CancellablePromise<void> {
    return $Call.ByID(269732774, archivePath);
}

export function SaveProfile(): $CancellablePromise<void> {
    return $Call.ByID(406053493);
}

export function SaveSettings(settings: config$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(1949631069, settings);
}

export function SelectArchives(): $CancellablePromise<string[] | null> {
    return $Call.ByID(4279671618);
}

export function SetActiveProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(3598325438, id);
}

export function SetApplication(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4121261467, app);
}

export function SetCategoryVisibility(id: string, visible: boolean): $CancellablePromise<void> {
    return $Call.ByID(4161271547, id, visible);
}

export function SetModCustomName(modID: string, customName: string): $CancellablePromise<void> {
    return $Call.ByID(193317225, modID, customName);
}

export function SetModEnabled(modID: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1151537538, modID, enabled);
}

export function SetNexusAPIKey(key: string): $CancellablePromise<void> {
    return $Call.ByID(127370205, key);
}

export function Startup(): $CancellablePromise<void> {
    return $Call.ByID(2154875234);
}

export function UnassignModFromCategory(categoryID: string, modID: string): $CancellablePromise<void> {
    return $Call.ByID(3431169981, categoryID, modID);
}

export function UpdateCategory(id: string, name: string, color: string, visible: boolean, sortOrder: number): $CancellablePromise<void> {
    return $Call.ByID(2178518964, id, name, color, visible, sortOrder);
}

export function UpdateMod(folderPath: string, archivePath: string, deleteOld: boolean): $CancellablePromise<void> {
    return $Call.ByID(1693017024, folderPath, archivePath, deleteOld);
}

export function ValidateNexusAPIKey(): $CancellablePromise<boolean> {
    return $Call.ByID(705135029);
}
