// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FilesDroppedPayload is emitted when OS files land on a data-file-drop-target zone.
 */
export interface FilesDroppedPayload {
    "files": string[] | null;
    "targetId": string;
}
