// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModUpdateResult from SMAPI mod update API.
 */
export interface ModUpdateResult {
    "uniqueId": string;
    "currentVersion": string;
    "latestVersion": string;

    /**
     * update, ok, incompatible, unofficial
     */
    "status": string;
    "modPageUrl": string;
    "message": string;
    "compatibilityStatus"?: string;
    "compatibilitySummary"?: string;
}

/**
 * UpdateInfo describes available SMAPI update.
 */
export interface UpdateInfo {
    "currentVersion": string;
    "latestVersion": string;
    "updateAvailable": boolean;
    "downloadUrl": string;
}
