// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ModUpdateResult from SMAPI mod update API.
 */
export class ModUpdateResult {
    /**
     * Creates a new ModUpdateResult instance.
     * @param {Partial<ModUpdateResult>} [$$source = {}] - The source object to create the ModUpdateResult.
     */
    constructor($$source = {}) {
        if (!("uniqueId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uniqueId"] = "";
        }
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * update, ok, incompatible
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("modPageUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modPageUrl"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModUpdateResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModUpdateResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModUpdateResult(/** @type {Partial<ModUpdateResult>} */($$parsedSource));
    }
}

/**
 * UpdateInfo describes available SMAPI update.
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("updateAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["updateAvailable"] = false;
        }
        if (!("downloadUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}
