// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Profile represents a mod loadout.
 */
export interface Profile {
    "id": string;
    "name": string;
    "enabledMods": { [_ in string]?: boolean } | null;
    "isActive": boolean;
}
