// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Profile represents a mod loadout.
 */
export class Profile {
    /**
     * Creates a new Profile instance.
     * @param {Partial<Profile>} [$$source = {}] - The source object to create the Profile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("enabledMods" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: boolean }}
             */
            this["enabledMods"] = {};
        }
        if (!("isActive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isActive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Profile}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("enabledMods" in $$parsedSource) {
            $$parsedSource["enabledMods"] = $$createField2_0($$parsedSource["enabledMods"]);
        }
        return new Profile(/** @type {Partial<Profile>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
