// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ContentPackFor {
    /**
     * Creates a new ContentPackFor instance.
     * @param {Partial<ContentPackFor>} [$$source = {}] - The source object to create the ContentPackFor.
     */
    constructor($$source = {}) {
        if (!("UniqueID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UniqueID"] = "";
        }
        if (!("MinimumVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["MinimumVersion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContentPackFor instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContentPackFor}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContentPackFor(/** @type {Partial<ContentPackFor>} */($$parsedSource));
    }
}

/**
 * DeleteModsResult summarizes bulk mod deletion.
 */
export class DeleteModsResult {
    /**
     * Creates a new DeleteModsResult instance.
     * @param {Partial<DeleteModsResult>} [$$source = {}] - The source object to create the DeleteModsResult.
     */
    constructor($$source = {}) {
        if (!("deletedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["deletedCount"] = 0;
        }
        if (!("archivesDeletedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["archivesDeletedCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["errors"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteModsResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeleteModsResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField2_0($$parsedSource["errors"]);
        }
        return new DeleteModsResult(/** @type {Partial<DeleteModsResult>} */($$parsedSource));
    }
}

/**
 * DependencyIssue describes an unsatisfied mod dependency.
 */
export class DependencyIssue {
    /**
     * Creates a new DependencyIssue instance.
     * @param {Partial<DependencyIssue>} [$$source = {}] - The source object to create the DependencyIssue.
     */
    constructor($$source = {}) {
        if (!("uniqueID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uniqueID"] = "";
        }
        if (!("minimumVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["minimumVersion"] = "";
        }
        if (!("isRequired" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRequired"] = false;
        }
        if (!("isContentPack" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isContentPack"] = false;
        }
        if (!("state" in $$source)) {
            /**
             * missing, version_too_low, disabled
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["installedName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["installedVersion"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["providerModId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["nexusModId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DependencyIssue instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DependencyIssue}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DependencyIssue(/** @type {Partial<DependencyIssue>} */($$parsedSource));
    }
}

/**
 * InstallDependencyPreview describes dependency warnings for a mod in an install queue.
 */
export class InstallDependencyPreview {
    /**
     * Creates a new InstallDependencyPreview instance.
     * @param {Partial<InstallDependencyPreview>} [$$source = {}] - The source object to create the InstallDependencyPreview.
     */
    constructor($$source = {}) {
        if (!("archivePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["archivePath"] = "";
        }
        if (!("modName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modName"] = "";
        }
        if (!("uniqueID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uniqueID"] = "";
        }
        if (!("issues" in $$source)) {
            /**
             * @member
             * @type {DependencyIssue[]}
             */
            this["issues"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallDependencyPreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstallDependencyPreview}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField3_0($$parsedSource["issues"]);
        }
        return new InstallDependencyPreview(/** @type {Partial<InstallDependencyPreview>} */($$parsedSource));
    }
}

/**
 * InstallResult describes an installed mod.
 */
export class InstallResult {
    /**
     * Creates a new InstallResult instance.
     * @param {Partial<InstallResult>} [$$source = {}] - The source object to create the InstallResult.
     */
    constructor($$source = {}) {
        if (!("folderPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folderPath"] = "";
        }
        if (!("modId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modId"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstallResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallResult(/** @type {Partial<InstallResult>} */($$parsedSource));
    }
}

/**
 * Manifest represents a SMAPI mod manifest.json.
 */
export class Manifest {
    /**
     * Creates a new Manifest instance.
     * @param {Partial<Manifest>} [$$source = {}] - The source object to create the Manifest.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Author"] = "";
        }
        if (!("Version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Version"] = "";
        }
        if (!("Description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Description"] = "";
        }
        if (!("UniqueID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UniqueID"] = "";
        }
        if (!("EntryDll" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["EntryDll"] = "";
        }
        if (!("UpdateKeys" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["UpdateKeys"] = [];
        }
        if (!("ContentPackFor" in $$source)) {
            /**
             * @member
             * @type {ContentPackFor | null}
             */
            this["ContentPackFor"] = null;
        }
        if (!("UpdateCautionMessage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdateCautionMessage"] = "";
        }
        if (!("Dependencies" in $$source)) {
            /**
             * @member
             * @type {ModDependency[]}
             */
            this["Dependencies"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manifest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Manifest}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType4;
        const $$createField9_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("UpdateKeys" in $$parsedSource) {
            $$parsedSource["UpdateKeys"] = $$createField6_0($$parsedSource["UpdateKeys"]);
        }
        if ("ContentPackFor" in $$parsedSource) {
            $$parsedSource["ContentPackFor"] = $$createField7_0($$parsedSource["ContentPackFor"]);
        }
        if ("Dependencies" in $$parsedSource) {
            $$parsedSource["Dependencies"] = $$createField9_0($$parsedSource["Dependencies"]);
        }
        return new Manifest(/** @type {Partial<Manifest>} */($$parsedSource));
    }
}

/**
 * Mod is a discovered mod with runtime state.
 */
export class Mod {
    /**
     * Creates a new Mod instance.
     * @param {Partial<Mod>} [$$source = {}] - The source object to create the Mod.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("folderPath" in $$source)) {
            /**
             * relative to mods root
             * @member
             * @type {string}
             */
            this["folderPath"] = "";
        }
        if (!("absolutePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["absolutePath"] = "";
        }
        if (!("manifest" in $$source)) {
            /**
             * @member
             * @type {Manifest}
             */
            this["manifest"] = (new Manifest());
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("categoryIds" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["categoryIds"] = [];
        }
        if (!("groupKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["groupKey"] = "";
        }
        if (!("groupLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["groupLabel"] = "";
        }
        if (!("updateStatus" in $$source)) {
            /**
             * @member
             * @type {UpdateStatus}
             */
            this["updateStatus"] = (new UpdateStatus());
        }
        if (!("hasConfig" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasConfig"] = false;
        }
        if (!("isCoreMod" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isCoreMod"] = false;
        }
        if (!("installTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["installTime"] = 0;
        }
        if (!("lastUpdated" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastUpdated"] = 0;
        }
        if (!("dependencyIssues" in $$source)) {
            /**
             * @member
             * @type {DependencyIssue[]}
             */
            this["dependencyIssues"] = [];
        }
        if (!("missingDependencyCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["missingDependencyCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["savedDownloadPath"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Mod instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Mod}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType7;
        const $$createField5_0 = $$createType0;
        const $$createField8_0 = $$createType8;
        const $$createField13_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("manifest" in $$parsedSource) {
            $$parsedSource["manifest"] = $$createField3_0($$parsedSource["manifest"]);
        }
        if ("categoryIds" in $$parsedSource) {
            $$parsedSource["categoryIds"] = $$createField5_0($$parsedSource["categoryIds"]);
        }
        if ("updateStatus" in $$parsedSource) {
            $$parsedSource["updateStatus"] = $$createField8_0($$parsedSource["updateStatus"]);
        }
        if ("dependencyIssues" in $$parsedSource) {
            $$parsedSource["dependencyIssues"] = $$createField13_0($$parsedSource["dependencyIssues"]);
        }
        return new Mod(/** @type {Partial<Mod>} */($$parsedSource));
    }
}

export class ModDependency {
    /**
     * Creates a new ModDependency instance.
     * @param {Partial<ModDependency>} [$$source = {}] - The source object to create the ModDependency.
     */
    constructor($$source = {}) {
        if (!("UniqueID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UniqueID"] = "";
        }
        if (!("MinimumVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["MinimumVersion"] = "";
        }
        if (!("IsRequired" in $$source)) {
            /**
             * nil = required (SMAPI default)
             * @member
             * @type {flexBool | null}
             */
            this["IsRequired"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModDependency instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModDependency}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModDependency(/** @type {Partial<ModDependency>} */($$parsedSource));
    }
}

/**
 * ModGroup is a collection of mods for UI grouping.
 */
export class ModGroup {
    /**
     * Creates a new ModGroup instance.
     * @param {Partial<ModGroup>} [$$source = {}] - The source object to create the ModGroup.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("mods" in $$source)) {
            /**
             * @member
             * @type {Mod[]}
             */
            this["mods"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModGroup}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("mods" in $$parsedSource) {
            $$parsedSource["mods"] = $$createField2_0($$parsedSource["mods"]);
        }
        return new ModGroup(/** @type {Partial<ModGroup>} */($$parsedSource));
    }
}

/**
 * UpdateStatus describes mod update state.
 */
export class UpdateStatus {
    /**
     * Creates a new UpdateStatus instance.
     * @param {Partial<UpdateStatus>} [$$source = {}] - The source object to create the UpdateStatus.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * current, update_available, incompatible, unofficial
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("modPageUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modPageUrl"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateStatus(/** @type {Partial<UpdateStatus>} */($$parsedSource));
    }
}

/**
 * flexBool accepts JSON booleans encoded as bool, string, or number.
 * @typedef {any} flexBool
 */

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = DependencyIssue.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ContentPackFor.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = ModDependency.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = Manifest.createFrom;
const $$createType8 = UpdateStatus.createFrom;
const $$createType9 = Mod.createFrom;
const $$createType10 = $Create.Array($$createType9);
