// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ContentPackFor {
    "UniqueID": string;
    "MinimumVersion": string;
}

/**
 * DeleteModsResult summarizes bulk mod deletion.
 */
export interface DeleteModsResult {
    "deletedCount": number;
    "archivesDeletedCount": number;
    "errors"?: string[] | null;
}

/**
 * DependencyIssue describes an unsatisfied mod dependency.
 */
export interface DependencyIssue {
    "uniqueID": string;
    "minimumVersion": string;
    "isRequired": boolean;
    "isContentPack": boolean;

    /**
     * missing, version_too_low, disabled
     */
    "state": string;
    "installedName"?: string;
    "installedVersion"?: string;
    "providerModId"?: string;
    "nexusModId"?: string;
}

/**
 * InstallDependencyPreview describes dependency warnings for a mod in an install queue.
 */
export interface InstallDependencyPreview {
    "archivePath": string;
    "modName": string;
    "uniqueID": string;
    "issues": DependencyIssue[] | null;
}

/**
 * InstallModNamePreview describes how a mod would be labeled under each naming strategy.
 */
export interface InstallModNamePreview {
    "officialName": string;
    "folderLabel": string;
    "destFolder": string;
    "uniqueID": string;
}

/**
 * InstallNamePreview summarizes install naming for one archive.
 */
export interface InstallNamePreview {
    "archivePath": string;
    "mods": InstallModNamePreview[] | null;
    "needsDisplayNameChoice": boolean;
}

/**
 * InstallResult describes an installed mod.
 */
export interface InstallResult {
    "folderPath": string;
    "modId": string;
    "name": string;
    "error"?: string;
}

/**
 * Manifest represents a SMAPI mod manifest.json.
 */
export interface Manifest {
    "Name": string;
    "Author": string;
    "Version": string;
    "Description": string;
    "UniqueID": string;
    "EntryDll": string;
    "UpdateKeys": string[] | null;
    "ContentPackFor": ContentPackFor | null;
    "UpdateCautionMessage": string;
    "Dependencies": ModDependency[] | null;
}

/**
 * Mod is a discovered mod with runtime state.
 */
export interface Mod {
    "id": string;

    /**
     * relative to mods root
     */
    "folderPath": string;
    "absolutePath": string;
    "manifest": Manifest;
    "enabled": boolean;
    "categoryIds": string[] | null;
    "groupKey": string;
    "groupLabel": string;
    "updateStatus": UpdateStatus;
    "hasConfig": boolean;
    "isCoreMod": boolean;
    "installTime": number;
    "lastUpdated": number;
    "dependencyIssues": DependencyIssue[] | null;
    "missingDependencyCount": number;
    "savedDownloadPath"?: string;
    "customName"?: string;
}

export interface ModDependency {
    "UniqueID": string;
    "MinimumVersion": string;

    /**
     * nil = required (SMAPI default)
     */
    "IsRequired": flexBool | null;
}

/**
 * ModGroup is a collection of mods for UI grouping.
 */
export interface ModGroup {
    "key": string;
    "label": string;
    "mods": Mod[] | null;
}

/**
 * UpdateStatus describes mod update state.
 */
export interface UpdateStatus {
    /**
     * current, update_available, incompatible, unofficial
     */
    "state": string;
    "latestVersion": string;
    "modPageUrl": string;
    "message": string;
}

/**
 * flexBool accepts JSON booleans encoded as bool, string, or number.
 */
export type flexBool = any;
