// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ContentPackFor {
    "UniqueID": string;
    "MinimumVersion": string;
}

/**
 * DeleteModsResult summarizes bulk mod deletion.
 */
export interface DeleteModsResult {
    "deletedCount": number;
    "archivesDeletedCount": number;
    "errors"?: string[] | null;
}

/**
 * DependencyIssue describes an unsatisfied mod dependency.
 */
export interface DependencyIssue {
    "uniqueID": string;
    "minimumVersion": string;
    "isRequired": boolean;
    "isContentPack": boolean;

    /**
     * missing, version_too_low, disabled
     */
    "state": string;
    "installedName"?: string;
    "installedVersion"?: string;
    "providerModId"?: string;
    "nexusModId"?: string;
}

/**
 * DuplicateModGroup describes multiple library folders sharing the same SMAPI UniqueID.
 */
export interface DuplicateModGroup {
    "uniqueID": string;
    "modName": string;
    "folders": string[] | null;
    "canonical": string;
}

/**
 * InstallDependencyPreview describes dependency warnings for a mod in an install queue.
 */
export interface InstallDependencyPreview {
    "archivePath": string;
    "modName": string;
    "uniqueID": string;
    "issues": DependencyIssue[] | null;
}

/**
 * InstallModNamePreview describes how a mod would be labeled under each naming strategy.
 */
export interface InstallModNamePreview {
    "officialName": string;
    "folderLabel": string;
    "destFolder": string;
    "uniqueID": string;
}

/**
 * InstallNamePreview summarizes install naming for one archive.
 */
export interface InstallNamePreview {
    "archivePath": string;
    "mods": InstallModNamePreview[] | null;
    "needsDisplayNameChoice": boolean;
}

/**
 * InstallOverwriteCandidate describes a mod folder that may receive merged patch files.
 */
export interface InstallOverwriteCandidate {
    "folderPath": string;
    "modName": string;
    "uniqueID": string;
    "matchedFiles": number;
    "totalFiles": number;
    "samplePaths"?: string[] | null;
}

/**
 * InstallOverwritePreview describes a no-manifest archive that may overwrite files in an installed mod.
 */
export interface InstallOverwritePreview {
    "archivePath": string;
    "fileCount": number;
    "candidates": InstallOverwriteCandidate[] | null;
    "suggestedTarget"?: string;

    /**
     * blocked | confirm
     */
    "state": string;
    "blockReason"?: string;
}

/**
 * InstallResult describes an installed mod.
 */
export interface InstallResult {
    "folderPath": string;
    "modId": string;
    "name": string;
    "error"?: string;
}

/**
 * Manifest represents a SMAPI mod manifest.json.
 */
export interface Manifest {
    "Name": string;
    "Author": string;
    "Version": string;
    "Description": string;
    "UniqueID": string;
    "EntryDll": string;
    "UpdateKeys": string[] | null;
    "ContentPackFor": ContentPackFor | null;
    "UpdateCautionMessage": string;
    "Dependencies": ModDependency[] | null;
}

/**
 * Mod is a discovered mod with runtime state.
 */
export interface Mod {
    "id": string;

    /**
     * relative to mods root
     */
    "folderPath": string;
    "absolutePath": string;
    "manifest": Manifest;
    "enabled": boolean;
    "categoryIds": string[] | null;
    "updateStatus": UpdateStatus;
    "hasConfig": boolean;
    "hasJsonFiles": boolean;
    "jsonFileCount": number;
    "isCoreMod": boolean;
    "installTime": number;
    "lastUpdated": number;
    "dependencyIssues": DependencyIssue[] | null;
    "missingDependencyCount": number;
    "packSiblingUIDs"?: string[] | null;
    "bundleChildren"?: Mod[] | null;
    "bundleNexusId"?: number;
    "enabledPartial"?: boolean;
    "enabledCount"?: number;
    "enabledTotal"?: number;
    "savedDownloadPath"?: string;
    "customName"?: string;
    "containsOverwrites": boolean;
    "resolvedNexusModId"?: number;
}

/**
 * ModConfigView is the payload for the integrated config editor.
 */
export interface ModConfigView {
    "modId": string;
    "modName": string;
    "folderPath": string;
    "relPath": string;
    "displayPath": string;
    "absolutePath": string;
    "content": string;
    "profileName": string;
    "profileSpecificConfigs": boolean;
}

export interface ModDependency {
    "UniqueID": string;
    "MinimumVersion": string;

    /**
     * nil = required (SMAPI default)
     */
    "IsRequired": flexBool | null;
}

/**
 * ModJsonFileNode is a folder or JSON file in a mod's config tree.
 */
export interface ModJsonFileNode {
    "name": string;
    "relPath"?: string;
    "isDir": boolean;
    "children"?: ModJsonFileNode[] | null;
}

/**
 * ModJsonSummary describes a mod that contains editable JSON files.
 */
export interface ModJsonSummary {
    "modId": string;
    "modName": string;
    "folderPath": string;
    "jsonFileCount": number;
}

/**
 * UpdateStatus describes mod update state.
 */
export interface UpdateStatus {
    /**
     * current, update_available, update_ignored, incompatible, unofficial
     */
    "state": string;
    "latestVersion": string;
    "modPageUrl": string;
    "message": string;
    "compatibilityStatus"?: string;
    "compatibilitySummary"?: string;
}

/**
 * flexBool accepts JSON booleans encoded as bool, string, or number.
 */
export type flexBool = any;
