// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModPage is a trimmed mod page record from the dataset.
 */
export interface ModPage {
    "site": string;
    "id": number;
    "name": string;
    "author": string;
    "pageUrl": string;
    "tagLine": string;
    "downloads": ModPageDownload[] | null;
}

/**
 * ModPageDownload summarizes one file on a mod page.
 */
export interface ModPageDownload {
    "id": number;
    "displayName": string;
    "fileName": string;
    "version": string;
    "type": string;
    "modCount": number;
}
