// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Category is a user-defined mod organization label.
 */
export interface Category {
    "id": string;
    "name": string;
    "color": string;
    "visible": boolean;
    "sortOrder": number;
    "modIds": string[] | null;
}
