// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DetectionResult holds auto-detected paths.
 */
export interface DetectionResult {
    "gamePath": string;
    "smapiPath": string;
    "modsRoot": string;
}

/**
 * Settings holds application configuration persisted to disk.
 */
export interface Settings {
    "gamePath": string;
    "smapiPath": string;
    "modsRoot": string;
    "ignoreHiddenFolders": boolean;
    "profileSpecificConfigs": boolean;
    "autoEnableOnInstall": boolean;
    "theme": string;
    "language": string;
    "showThumbnails": boolean;
    "autoSaveProfileChanges": boolean;
    "alwaysAskDeleteOnUpdate": boolean;
    "showInstallSummary": boolean;
    "hideDisabledFilter": string;
    "visibleColumns": string[] | null;
    "windowWidth": number;
    "windowHeight": number;
    "setupComplete": boolean;
    "lastUpdateCheck": number;

    /**
     * Nexus mod ID -> ignored latest version
     */
    "ignoredModUpdates"?: { [_ in string]?: string } | null;
}
