// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DetectionResult holds auto-detected paths.
 */
export class DetectionResult {
    /**
     * Creates a new DetectionResult instance.
     * @param {Partial<DetectionResult>} [$$source = {}] - The source object to create the DetectionResult.
     */
    constructor($$source = {}) {
        if (!("gamePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gamePath"] = "";
        }
        if (!("smapiPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["smapiPath"] = "";
        }
        if (!("modsRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modsRoot"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetectionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DetectionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DetectionResult(/** @type {Partial<DetectionResult>} */($$parsedSource));
    }
}

/**
 * Settings holds application configuration persisted to disk.
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("gamePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gamePath"] = "";
        }
        if (!("smapiPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["smapiPath"] = "";
        }
        if (!("modsRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modsRoot"] = "";
        }
        if (!("ignoreHiddenFolders" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ignoreHiddenFolders"] = false;
        }
        if (!("profileSpecificConfigs" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["profileSpecificConfigs"] = false;
        }
        if (!("autoEnableOnInstall" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoEnableOnInstall"] = false;
        }
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("showThumbnails" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showThumbnails"] = false;
        }
        if (!("autoSaveProfileChanges" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoSaveProfileChanges"] = false;
        }
        if (!("alwaysAskDeleteOnUpdate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysAskDeleteOnUpdate"] = false;
        }
        if (!("modGrouping" in $$source)) {
            /**
             * folder, contentpack, folder_condensed
             * @member
             * @type {string}
             */
            this["modGrouping"] = "";
        }
        if (!("hideDisabledFilter" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hideDisabledFilter"] = "";
        }
        if (!("visibleColumns" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["visibleColumns"] = [];
        }
        if (!("windowWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowWidth"] = 0;
        }
        if (!("windowHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowHeight"] = 0;
        }
        if (!("setupComplete" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["setupComplete"] = false;
        }
        if (!("lastUpdateCheck" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastUpdateCheck"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField13_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("visibleColumns" in $$parsedSource) {
            $$parsedSource["visibleColumns"] = $$createField13_0($$parsedSource["visibleColumns"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
