// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as categories$0 from "../categories/models.js";

export function AssignModToCategory(categoryID: string, modID: string): $CancellablePromise<void> {
    return $Call.ByID(1193757383, categoryID, modID);
}

export function CreateCategory(name: string, color: string): $CancellablePromise<categories$0.Category> {
    return $Call.ByID(173689607, name, color);
}

export function DeleteCategory(id: string): $CancellablePromise<void> {
    return $Call.ByID(344184136, id);
}

export function ListCategories(): $CancellablePromise<categories$0.Category[] | null> {
    return $Call.ByID(2564695223);
}

export function ReorderCategories(ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(361474690, ids);
}

export function SetCategoryVisibility(id: string, visible: boolean): $CancellablePromise<void> {
    return $Call.ByID(741332269, id, visible);
}

export function UnassignModFromCategory(categoryID: string, modID: string): $CancellablePromise<void> {
    return $Call.ByID(673976131, categoryID, modID);
}

export function UpdateCategory(id: string, name: string, color: string, visible: boolean, sortOrder: number): $CancellablePromise<void> {
    return $Call.ByID(3809705130, id, name, color, visible, sortOrder);
}
