// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mods$0 from "../mods/models.js";

export function ConfigEditorIsDirty(): $CancellablePromise<boolean> {
    return $Call.ByID(2750464381);
}

export function GetModConfig(modID: string): $CancellablePromise<mods$0.ModConfigView> {
    return $Call.ByID(906105186, modID);
}

export function GetModConfigFile(modID: string, relPath: string): $CancellablePromise<mods$0.ModConfigView> {
    return $Call.ByID(1256409092, modID, relPath);
}

export function ListModJsonFiles(modID: string): $CancellablePromise<mods$0.ModJsonFileNode[] | null> {
    return $Call.ByID(3679573429, modID);
}

export function ListModsWithJsonFiles(): $CancellablePromise<mods$0.ModJsonSummary[] | null> {
    return $Call.ByID(4107634770);
}

export function OpenModConfigEditor(modID: string): $CancellablePromise<void> {
    return $Call.ByID(440657207, modID);
}

export function OpenModConfigEditorFile(modID: string, relPath: string): $CancellablePromise<void> {
    return $Call.ByID(2858604809, modID, relPath);
}

export function OpenModConfigExternal(modID: string): $CancellablePromise<void> {
    return $Call.ByID(2039488469, modID);
}

export function OpenModConfigExternalFile(modID: string, relPath: string): $CancellablePromise<void> {
    return $Call.ByID(2164781747, modID, relPath);
}

export function ReloadConfigEditor(): $CancellablePromise<void> {
    return $Call.ByID(3843597022);
}

export function SaveModConfig(modID: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(961995421, modID, content);
}

export function SaveModConfigFile(modID: string, relPath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1035798107, modID, relPath, content);
}

export function SetConfigEditorDirty(dirty: boolean): $CancellablePromise<void> {
    return $Call.ByID(777102457, dirty);
}
