// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as moddataset$0 from "../moddataset/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mods$0 from "../mods/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profiles$0 from "../profiles/models.js";

export function CleanupDuplicateModGroup(keepFolder: string): $CancellablePromise<void> {
    return $Call.ByID(1168902372, keepFolder);
}

export function DeleteMod(folderPath: string, deleteArchive: boolean): $CancellablePromise<void> {
    return $Call.ByID(3562131751, folderPath, deleteArchive);
}

export function DeleteMods(folderPaths: string[] | null, deleteArchives: boolean): $CancellablePromise<mods$0.DeleteModsResult> {
    return $Call.ByID(2429323068, folderPaths, deleteArchives);
}

export function DuplicateModCount(): $CancellablePromise<number> {
    return $Call.ByID(446238588);
}

export function GetModDatasetPage(uniqueID: string): $CancellablePromise<moddataset$0.ModPage> {
    return $Call.ByID(120516253, uniqueID);
}

export function InstallMods(archivePaths: string[] | null, useFolderDisplayNames: boolean, overwriteTargets: { [_ in string]?: string[] | null } | null): $CancellablePromise<mods$0.InstallResult[] | null> {
    return $Call.ByID(2755729680, archivePaths, useFolderDisplayNames, overwriteTargets);
}

export function ListDuplicateMods(): $CancellablePromise<mods$0.DuplicateModGroup[] | null> {
    return $Call.ByID(2309681118);
}

export function ListMods(search: string, hideDisabled: string): $CancellablePromise<mods$0.Mod[] | null> {
    return $Call.ByID(3941201543, search, hideDisabled);
}

export function ListUnmanagedMods(): $CancellablePromise<profiles$0.UnmanagedMod[] | null> {
    return $Call.ByID(3379482647);
}

export function ModsIncompatible(): $CancellablePromise<number> {
    return $Call.ByID(2877220190);
}

export function ModsReadyToUpdate(): $CancellablePromise<number> {
    return $Call.ByID(4177265310);
}

export function ModsWithDependencyIssues(): $CancellablePromise<number> {
    return $Call.ByID(2081026994);
}

export function OpenActiveModsFolder(): $CancellablePromise<void> {
    return $Call.ByID(819187301);
}

export function OpenManifest(folderPath: string): $CancellablePromise<void> {
    return $Call.ByID(29979383, folderPath);
}

export function OpenModFolder(folderPath: string): $CancellablePromise<void> {
    return $Call.ByID(2028440906, folderPath);
}

export function PreviewInstallDependencies(archivePaths: string[] | null): $CancellablePromise<mods$0.InstallDependencyPreview[] | null> {
    return $Call.ByID(3167963324, archivePaths);
}

export function PreviewInstallNames(archivePaths: string[] | null): $CancellablePromise<mods$0.InstallNamePreview[] | null> {
    return $Call.ByID(261612779, archivePaths);
}

export function PreviewInstallOverwrites(archivePaths: string[] | null): $CancellablePromise<mods$0.InstallOverwritePreview[] | null> {
    return $Call.ByID(3260430463, archivePaths);
}

export function SetModCustomName(modID: string, customName: string): $CancellablePromise<void> {
    return $Call.ByID(4190845754, modID, customName);
}

export function SetModEnabled(modID: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3483913367, modID, enabled);
}

export function UnmanagedModCount(): $CancellablePromise<number> {
    return $Call.ByID(1960806233);
}

export function UpdateMod(folderPath: string, archivePath: string, deleteOld: boolean): $CancellablePromise<void> {
    return $Call.ByID(2393606949, folderPath, archivePath, deleteOld);
}
