// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nexus$0 from "../nexus/models.js";

export function DeleteSavedDownload(archivePath: string): $CancellablePromise<void> {
    return $Call.ByID(685726642, archivePath);
}

export function DownloadModUpdate(updateKey: string, modName: string): $CancellablePromise<string> {
    return $Call.ByID(1123774313, updateKey, modName);
}

export function EndorseMod(updateKey: string, version: string): $CancellablePromise<void> {
    return $Call.ByID(109455952, updateKey, version);
}

export function GetInstallSuggestedTags(archivePaths: string[] | null, modIDs: number[] | null): $CancellablePromise<string[] | null> {
    return $Call.ByID(21155711, archivePaths, modIDs);
}

export function GetNexusSuggestedTags(modIDs: number[] | null): $CancellablePromise<string[] | null> {
    return $Call.ByID(45172019, modIDs);
}

export function HandleNXMURL(url: string): $CancellablePromise<string> {
    return $Call.ByID(614382860, url);
}

export function IsNexusConnected(): $CancellablePromise<boolean> {
    return $Call.ByID(595791662);
}

export function ListDownloads(): $CancellablePromise<nexus$0.DownloadEntry[] | null> {
    return $Call.ByID(1088556221);
}

export function ListSavedDownloads(): $CancellablePromise<nexus$0.DownloadRecord[] | null> {
    return $Call.ByID(1296737656);
}

export function ProbeNexusAPIKey(): $CancellablePromise<boolean> {
    return $Call.ByID(1544399946);
}

export function RevealArchiveInFileManager(archivePath: string): $CancellablePromise<void> {
    return $Call.ByID(2856919411, archivePath);
}

export function SelectArchives(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1562641659);
}

export function SetNexusAPIKey(key: string): $CancellablePromise<void> {
    return $Call.ByID(3163351584, key);
}

export function ValidateNexusAPIKey(): $CancellablePromise<boolean> {
    return $Call.ByID(3958226334);
}
