// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profiles$0 from "../profiles/models.js";

export function CreateProfile(name: string): $CancellablePromise<profiles$0.Profile> {
    return $Call.ByID(908347638, name);
}

export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(2352280599, id);
}

export function ListProfiles(): $CancellablePromise<profiles$0.Profile[] | null> {
    return $Call.ByID(3984103715);
}

export function RenameProfile(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2140796748, id, name);
}

export function SaveProfile(): $CancellablePromise<void> {
    return $Call.ByID(3323669245);
}

export function SetActiveProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(175415558, id);
}
