// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

export function BrowseGameFolder(): $CancellablePromise<string> {
    return $Call.ByID(720270022);
}

export function BrowseModsRoot(): $CancellablePromise<string> {
    return $Call.ByID(3911713777);
}

export function BrowseSMAPIPath(): $CancellablePromise<string> {
    return $Call.ByID(2341988007);
}

export function CompleteSetup(gamePath: string, smapiPath: string, modsRoot: string): $CancellablePromise<void> {
    return $Call.ByID(2560108558, gamePath, smapiPath, modsRoot);
}

export function DetectPaths(): $CancellablePromise<config$0.DetectionResult> {
    return $Call.ByID(2134194683);
}

export function GetSettings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(2578468823);
}

export function SaveSettings(settings: config$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(140310686, settings);
}
