// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as smapi$0 from "../smapi/models.js";

export function CheckModUpdates(): $CancellablePromise<smapi$0.ModUpdateResult[] | null> {
    return $Call.ByID(4034001243);
}

export function CheckSMAPIUpdate(): $CancellablePromise<smapi$0.UpdateInfo> {
    return $Call.ByID(1604082198);
}

export function GetSMAPIVersion(): $CancellablePromise<string> {
    return $Call.ByID(991768449);
}

export function InstallSMAPI(): $CancellablePromise<void> {
    return $Call.ByID(2272390566);
}

export function LaunchSMAPI(): $CancellablePromise<void> {
    return $Call.ByID(3312791096);
}

export function SetModUpdateIgnored(modID: string, ignored: boolean): $CancellablePromise<void> {
    return $Call.ByID(565694916, modID, ignored);
}
