// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function CheckAppUpdate(): $CancellablePromise<string> {
    return $Call.ByID(4056207848);
}

export function EmitNXMURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(3339689491, url);
}

export function ProcessCommandLineArgs(args: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3868848143, args);
}

export function RegisterNXMProtocol(): $CancellablePromise<void> {
    return $Call.ByID(3706747988);
}
