// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadEntry tracks a download.
 */
export interface DownloadEntry {
    "id": string;
    "modName": string;
    "url": string;
    "status": string;
    "progress": number;
    "filePath": string;
    "startedAt": number;
}

/**
 * DownloadRecord links a saved archive to mod identity metadata.
 */
export interface DownloadRecord {
    "archivePath": string;
    "nexusModId"?: number;
    "uniqueId"?: string;
    "fileName"?: string;
    "downloadedAt": number;
}
