// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DownloadEntry tracks a download.
 */
export class DownloadEntry {
    /**
     * Creates a new DownloadEntry instance.
     * @param {Partial<DownloadEntry>} [$$source = {}] - The source object to create the DownloadEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("modName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modName"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("progress" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadEntry(/** @type {Partial<DownloadEntry>} */($$parsedSource));
    }
}

/**
 * DownloadRecord links a saved archive to mod identity metadata.
 */
export class DownloadRecord {
    /**
     * Creates a new DownloadRecord instance.
     * @param {Partial<DownloadRecord>} [$$source = {}] - The source object to create the DownloadRecord.
     */
    constructor($$source = {}) {
        if (!("archivePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["archivePath"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["nexusModId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["uniqueId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["fileName"] = undefined;
        }
        if (!("downloadedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downloadedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadRecord(/** @type {Partial<DownloadRecord>} */($$parsedSource));
    }
}
